version: '2'

services:
  bind:
    restart: always
    build: .
    network_mode: "host"
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - ./named.conf:/etc/bind/named.conf
    - ./arnaud-ruffat.local.db:/etc/bind/arnaud-ruffat.local.db
    - ./10.203.db:/etc/bind/10.203.db
