version: '2'

services:
  bind:
    restart: always
    build: ./bind/
    networks:
      net205:
        ipv4_address: 10.205.3.2
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - ./bind/named.conf:/etc/bind/named.conf
    - ./bind/arnaud-ruffat.local.db:/etc/bind/arnaud-ruffat.local.db
    - ./bind/10.205.db:/etc/bind/10.205.db

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: arnaud-ruffat.local
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "110:110"
      - "995:995"
    volumes:
      - ./mail/data:/var/mail
      - ./mail/state:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_POP3=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=empty
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      net205:
        ipv4_address: 10.205.3.3

networks:
  net205:
    external: true
